language: php

php:
  - 5.3
  - 5.4

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar

script: ./bin/tests.sh
